name: Release

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to build (optional)"
        required: false
        default: ""

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.platform }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux-x86_64
            binary_name: agent-sync-linux-x86_64
          - os: macos-latest
            platform: darwin-arm64
            binary_name: agent-sync-darwin-arm64
          - os: windows-latest
            platform: windows-x86_64
            binary_name: agent-sync-windows-x86_64.exe
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5

      - name: Install dependencies
        run: opam install . --deps-only --with-test

      - name: Build
        run: opam exec -- dune build

      - name: Run tests
        run: opam exec -- dune runtest

      - name: Install
        run: opam install . --destdir _install

      - name: Package binary (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          mkdir -p release
          cp _install/bin/agent-sync release/${{ matrix.binary_name }}
          chmod +x release/${{ matrix.binary_name }}
          tar -czf agent-sync-${{ matrix.platform }}.tar.gz -C release ${{ matrix.binary_name }}
          sha256sum agent-sync-${{ matrix.platform }}.tar.gz > agent-sync-${{ matrix.platform }}.tar.gz.sha256

      - name: Package binary (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir -p release
          copy _install\bin\agent-sync.exe\release\${{ matrix.binary_name }}
          7z a agent-sync-${{ matrix.platform }}.zip release\${{ matrix.binary_name }}
          sha256sum agent-sync-${{ matrix.platform }}.zip > agent-sync-${{ matrix.platform }}.zip.sha256

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./agent-sync-${{ matrix.platform }}.${{ matrix.os == 'windows-latest' && 'zip' || 'tar.gz' }}
            ./agent-sync-${{ matrix.platform }}.${{ matrix.os == 'windows-latest' && 'zip' || 'tar.gz' }}.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
